version: "3.9"
services:
  backend:
    build: .
    depends_on:
      - db
    container_name: "football-app-backend"
    ports:
      - "5000:5000"
    environment:
      - host=db
      - port=27017
      - db=football-app-ab
  db:
    image: "mongo:latest"
    container_name: "football-app-db"
    environment: 
      - MONGO_INITDB_DATABASE=football-app-db
    ports: 
      - "27017:27017"